[package]
name = "titi-ffi"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false
rust-version.workspace = true

[lib]
name = "titi_ffi"
crate-type = ["cdylib", "staticlib", "rlib"]

[dependencies]
titi-core = { workspace = true, features = ["opus"] }
uniffi = { workspace = true }
thiserror = { workspace = true }

[build-dependencies]
uniffi = { workspace = true, features = ["build"] }

[[bin]]
name = "uniffi-bindgen"
path = "src/bin/uniffi_bindgen.rs"
required-features = ["cli"]

[features]
cli = ["uniffi/cli"]
