import Foundation
import Observation
import TitiFrame

// `TitiEngine`, `FfiAction`, `FfiUiEvent`, … come from the uniffi-generated
// titi_ffi.swift placed in Sources/TitiCore/Generated by scripts/ios-build-core.sh.

public enum FloorState: Sendable { case idle, pending, talking, busy, queued }

public struct Peer: Identifiable, Sendable { public var id: String { node }; public let node: String; public var name: String; public var hue: Int; public var link: FfiLinkClass; public var inGroup: Bool; public var bars: Int = 0; public var hops: Int = 0 }
public struct Invite: Identifiable, Sendable { public var id: String { group }; public let group: String; public let name: String; public let host: String; public let hostName: String; public let members: Int }
public struct Member: Identifiable, Sendable { public var id: String { node }; public let node: String; public let name: String; public let hue: Int }
public struct ChatMessage: Identifiable, Sendable { public let id: String; public let group: String; public let from: String; public let fromName: String; public let sentMs: UInt64; public let body: FfiMessageBody; public let mine: Bool; public var acked = false }

public struct GroupState: Identifiable, Sendable {
    public let id: String
    public var name: String
    public var fullDuplex: Bool
    public var isCreator: Bool
    public var members: [Member]
    public var floor: FloorState = .idle
    public var talkerName: String?
    public var talkerNode: String?
    public var handover = "stable"
    public var link: FfiLinkClass?
    public var suspended = false
    public var unread = 0
}

/// Owns the Rust engine. All engine calls run on `q` (serial) so the core
/// stays single-threaded; published state is updated on the main actor.
@Observable
public final class EngineHost: @unchecked Sendable, TransportEvents {
    public private(set) var nodeId = ""
    public var groups: [GroupState] = []
    public var activeGroup: String?
    public var peers: [String: Peer] = [:]
    public var invites: [Invite] = []
    public var messages: [ChatMessage] = []
    public var levelDbfs: Float = -60
    public var muted = false { didSet { audio.muted = muted } }
    public var running = false
    public var toast: String?
    public var active: GroupState? { groups.first { $0.id == activeGroup } }

    public let engine: TitiEngine
    public let audio = AudioEngine()
    private let q = DispatchQueue(label: "titi.engine", qos: .userInteractive)
    private var transports: [UInt32: any Transport] = [:]
    private var tick: DispatchSourceTimer?
    private var names: [String: String] = [:]
    private var pendingCode: (String, Date)?
    private let defaults = UserDefaults.standard

    public init(displayName: String, hue: Int) throws {
        let seed = defaults.data(forKey: "identity_seed").map { [UInt8]($0) } ?? []
        engine = try TitiEngine(seed: seed, displayName: displayName, avatarHue: UInt16(hue), rngSeed: UInt64.random(in: 0...UInt64.max))
        if seed.isEmpty { defaults.set(Data(engine.identitySeed()), forKey: "identity_seed") }
        nodeId = engine.nodeId().hex
        if let g = defaults.data(forKey: "groups_blob") { try? engine.restoreGroups(data: [UInt8](g), nowMs: now()) }
        audio.onPcm = { [weak self] pcm, t in self?.post { self?.apply(self!.engine.onAudioIn(pcmLe: pcm.leBytes, nowMs: t)) } }
        refreshGroups()
    }

    private func now() -> UInt64 { UInt64(Date().timeIntervalSince1970 * 1000) }
    private func post(_ f: @escaping @Sendable () -> Void) { q.async(execute: f) }

    // MARK: lifecycle
    public func start(_ ts: [any Transport]) {
        guard !running else { return }
        running = true
        try? audio.start()
        for t in ts { transports[t.linkId] = t; t.start(self) }
        let timer = DispatchSource.makeTimerSource(queue: q)
        var n = 0
        timer.schedule(deadline: .now(), repeating: .milliseconds(20), leeway: .milliseconds(2))
        timer.setEventHandler { [weak self] in
            guard let self else { return }
            self.apply(self.engine.tick(nowMs: self.now()))
            n += 1
            if n % 500 == 0 { self.syncRelayRooms() }
        }
        timer.resume()
        tick = timer
        post { self.syncRelayRooms() }
    }

    public func stop() {
        tick?.cancel(); tick = nil
        transports.values.forEach { $0.stop() }; transports.removeAll()
        audio.stop()
        running = false
    }

    // MARK: transport events
    public func linkUp(_ t: any Transport) { post { self.apply(self.engine.onLinkUp(link: t.linkId, class: t.linkClass, mtu: t.mtu, nowMs: self.now())) } }
    public func linkDown(_ t: any Transport) { post { self.apply(self.engine.onLinkDown(link: t.linkId, nowMs: self.now())) } }
    public func peerSeen(_ t: any Transport, token: String) { post { self.apply(self.engine.onPeerSeen(link: t.linkId, token: token, nowMs: self.now())) } }
    public func peerLost(_ t: any Transport, token: String) { post { self.apply(self.engine.onPeerLost(link: t.linkId, token: token, nowMs: self.now())) } }
    public func frame(_ t: any Transport, token: String, bytes: [UInt8]) { post { self.apply(self.engine.onFrame(link: t.linkId, token: token, bytes: bytes, nowMs: self.now())) } }

    // MARK: intents
    public func pttDown(_ prio: FfiPriority = .normal) { post { self.apply(self.engine.pttDown(prio: prio, nowMs: self.now())) } }
    public func pttUp() { post { self.apply(self.engine.pttUp(nowMs: self.now())) } }
    public func createGroup(_ name: String) { post { self.tryApply { try self.engine.createGroup(name: name, nowMs: self.now()) }; self.refreshGroups(); self.syncRelayRooms() } }
    public func dissolveGroup(_ id: String) { post { self.tryApply { try self.engine.dissolveGroup(group: [UInt8](hex: id)!, nowMs: self.now()) }; self.refreshGroups(); self.syncRelayRooms() } }
    public func leaveGroup(_ id: String) { post { self.tryApply { try self.engine.leaveGroup(group: [UInt8](hex: id)!, nowMs: self.now()) }; self.refreshGroups(); self.syncRelayRooms() } }
    public func setActiveGroup(_ id: String) { post { try? self.engine.setActiveGroup(group: [UInt8](hex: id)!); self.refreshGroups(); self.syncRelayRooms(); self.update(id) { $0.unread = 0 } } }
    public func setFullDuplex(_ id: String, _ on: Bool) { post { self.tryApply { try self.engine.setFullDuplex(group: [UInt8](hex: id)!, on: on, nowMs: self.now()) }; self.refreshGroups() } }
    public func invitePeer(_ g: String, _ node: String) { post { self.tryApply { try self.engine.invitePeer(group: [UInt8](hex: g)!, node: [UInt8](hex: node)!, nowMs: self.now()) } } }
    public func acceptInvite(_ i: Invite) { Task { @MainActor in invites.removeAll { $0.group == i.group } }; post { self.tryApply { try self.engine.acceptInvite(group: [UInt8](hex: i.group)!, host: [UInt8](hex: i.host)!, nowMs: self.now()) } } }
    public func declineInvite(_ i: Invite) { Task { @MainActor in invites.removeAll { $0.group == i.group } }; post { _ = try? self.engine.declineInvite(group: [UInt8](hex: i.group)!, host: [UInt8](hex: i.host)!, nowMs: self.now()) } }
    public func joinByLink(_ url: String) { post { self.apply(self.engine.joinByLink(url: url, nowMs: self.now())) } }
    public func joinByCode(_ code: String) {
        post {
            self.pendingCode = (code, Date().addingTimeInterval(120)); self.syncRelayRooms()
            self.apply(self.engine.joinByCode(code: code, nowMs: self.now()))
        }
        // retry every 3 s while the rendezvous brings the host in
        let t = DispatchSource.makeTimerSource(queue: q)
        t.schedule(deadline: .now() + 3, repeating: 3)
        t.setEventHandler { [weak self] in
            guard let self, let (c, until) = self.pendingCode else { t.cancel(); return }
            if Date() > until || (self.active?.members.count ?? 0) > 1 { self.pendingCode = nil; self.syncRelayRooms(); t.cancel(); return }
            self.apply(self.engine.joinByCode(code: c, nowMs: self.now()))
        }
        t.resume()
    }
    public func sendText(_ g: String, _ text: String) { post { self.tryApply { try self.engine.sendText(group: [UInt8](hex: g)!, text: text, nowMs: self.now()) } } }
    public func sendSos(_ g: String, lat: Double, lon: Double) { post { self.tryApply { try self.engine.sendSos(group: [UInt8](hex: g)!, lat: lat, lon: lon, note: "", cancelled: false, nowMs: self.now()) }; self.apply(self.engine.pttDown(prio: .emergency, nowMs: self.now())) } }
    public func currentCode(_ g: String) -> (String, Int)? { guard let s = try? engine.currentCode(group: [UInt8](hex: g)!, nowMs: now()) else { return nil }; let p = s.split(separator: "|"); return (String(p[0]), Int(p.count > 1 ? p[1] : "0") ?? 0) }
    public func deepLink(_ g: String) -> String? { try? engine.deepLink(group: [UInt8](hex: g)!, nowMs: now(), validMs: 600_000) }

    // MARK: dispatch
    private func tryApply(_ f: () throws -> [FfiAction]) { do { apply(try f()) } catch { Task { @MainActor in self.toast = "\(error)" } } }

    private func apply(_ acts: [FfiAction]) {
        for a in acts {
            switch a {
            case let .send(link, peer, bytes): transports[link]?.send(peer: peer, bytes: bytes)
            case let .play(pcmLe): audio.play(pcmLe.int16s)
            case let .capture(active, _): active ? audio.startCapture() : audio.stopCapture()
            case let .persist(key, value): if key == "groups" { defaults.set(Data(value), forKey: "groups_blob") }
            case .wakeAt: break
            case let .ui(e): onUi(e)
            }
        }
    }

    private func onUi(_ e: FfiUiEvent) {
        Task { @MainActor [self] in
            switch e {
            case let .peerDiscovered(node, name, hue, link, inGroup):
                let id = node.hex; names[id] = name
                var p = peers[id] ?? Peer(node: id, name: name, hue: Int(hue), link: link, inGroup: inGroup)
                p.name = name; p.hue = Int(hue); p.link = link; p.inGroup = inGroup; peers[id] = p
            case let .peerLost(node): peers.removeValue(forKey: node.hex)
            case let .peerLink(node, link, bars, hops): if var p = peers[node.hex] { p.link = link; p.bars = Int(bars); p.hops = Int(hops); peers[node.hex] = p }
            case .floorGranted: updateActive { $0.floor = .talking; $0.talkerNode = nodeId; $0.talkerName = nil }
            case .floorDenied: updateActive { $0.floor = .busy }
            case let .floorTaken(group, holder, name, _): names[holder.hex] = name; update(group.hex) { $0.floor = holder.hex == nodeId ? .talking : .busy; $0.talkerName = name; $0.talkerNode = holder.hex }
            case let .floorIdle(group): update(group.hex) { $0.floor = .idle; $0.talkerName = nil; $0.talkerNode = nil }
            case .talkWarning: toast = "10 seconds left"
            case .talkTimeout: toast = "Talk time limit reached"
            case let .inviteOffered(group, name, host, hostName, members):
                invites.removeAll { $0.group == group.hex }; invites.append(Invite(group: group.hex, name: name, host: host.hex, hostName: hostName, members: Int(members)))
            case let .joined(_, name): refreshGroups(); syncRelayRooms(); toast = "Joined \(name)"
            case let .joinFailed(reason): toast = "Could not join: \(reason)"
            case let .memberJoined(_, node, name): names[node.hex] = name; refreshGroups()
            case .memberLeft: refreshGroups()
            case let .groupDissolved(_, name): refreshGroups(); syncRelayRooms(); toast = "“\(name)” was deleted by its creator"
            case let .message(group, from, uuid, sentMs, body):
                let m = ChatMessage(id: uuid.hex, group: group.hex, from: from.hex, fromName: names[from.hex] ?? String(from.hex.prefix(6)), sentMs: sentMs, body: body, mine: from.hex == nodeId)
                messages.append(m); if messages.count > 500 { messages.removeFirst() }
                if !m.mine && activeGroup != group.hex { update(group.hex) { $0.unread += 1 } }
            case let .messageAcked(uuid, _): if let i = messages.firstIndex(where: { $0.id == uuid.hex }) { messages[i].acked = true }
            case let .handover(group, state, link, _): update(group.hex) { $0.handover = state; $0.link = link }
            case let .suspended(group): update(group.hex) { $0.suspended = true }
            case let .resumed(group): update(group.hex) { $0.suspended = false }
            case let .modeChanged(group, fd): update(group.hex) { $0.fullDuplex = fd }
            case let .level(_, dbfs): levelDbfs = dbfs
            case let .error(message): toast = message
            }
        }
    }

    private func refreshGroups() {
        let gs = engine.groups()
        Task { @MainActor [self] in
            let prev = Dictionary(uniqueKeysWithValues: groups.map { ($0.id, $0) })
            groups = gs.map { g in
                let id = g.id.hex
                let members = ((try? engine.members(group: g.id)) ?? []).map { Member(node: $0.node.hex, name: $0.name, hue: Int($0.hue)) }
                members.forEach { names[$0.node] = $0.name }
                var s = prev[id] ?? GroupState(id: id, name: g.name, fullDuplex: g.fullDuplex, isCreator: g.isCreator, members: members)
                s.name = g.name; s.fullDuplex = g.fullDuplex; s.isCreator = g.isCreator; s.members = members
                return s
            }
            activeGroup = gs.first { $0.isActive }?.id.hex
        }
    }

    private func syncRelayRooms() {
        guard let relay = transports[LinkIds.internet] as? RelayTransport else { return }
        var rooms: [(hash: [UInt8], rendezvous: Bool)] = []
        for g in engine.groups() {
            if let h = try? groupHash(group: g.id) { rooms.append((h, false)) }
            for h in (try? engine.rendezvousForGroup(group: g.id, nowMs: now())) ?? [] { rooms.append((h, true)) }
        }
        if let (c, _) = pendingCode { for h in rendezvousForCode(code: c, nowMs: now()) { rooms.append((h, true)) } }
        relay.setRooms(rooms)
    }

    @MainActor private func updateActive(_ f: (inout GroupState) -> Void) { if let a = activeGroup { update(a, f) } }
    @MainActor private func update(_ id: String, _ f: (inout GroupState) -> Void) { if let i = groups.firstIndex(where: { $0.id == id }) { f(&groups[i]) } }
}

extension Array where Element == Int16 {
    var leBytes: [UInt8] { var o = [UInt8](); o.reserveCapacity(count * 2); for s in self { let u = UInt16(bitPattern: s); o.append(UInt8(u & 0xFF)); o.append(UInt8(u >> 8)) }; return o }
}
extension Array where Element == UInt8 {
    var int16s: [Int16] { stride(from: 0, to: count - 1, by: 2).map { Int16(bitPattern: UInt16(self[$0]) | UInt16(self[$0 + 1]) << 8) } }
}
